param(
  [string]$AppUrl,
  [string]$ApiBase,
  [string]$AndroidSdkPath
)

$ErrorActionPreference = "Stop"

$repoMobileDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRootDir = Split-Path -Parent $repoMobileDir

$appUrlValue = [string]$AppUrl
$apiBaseValue = [string]$ApiBase
$appUrlValue = $appUrlValue.Trim()
$apiBaseValue = $apiBaseValue.Trim()

if ($appUrlValue -and -not ($appUrlValue.StartsWith("https://") -or $appUrlValue.StartsWith("http://"))) {
  throw "AppUrl must start with https:// or http://"
}

if ($apiBaseValue -and -not ($apiBaseValue.StartsWith("https://") -or $apiBaseValue.StartsWith("http://"))) {
  throw "ApiBase must start with https:// or http://"
}

if ($apiBaseValue) {
  $apiBaseValue = $apiBaseValue.TrimEnd("/")
  if (-not $apiBaseValue.ToLower().EndsWith("/api")) {
    $apiBaseValue = "$apiBaseValue/api"
  }
}

if (-not $AndroidSdkPath -or [string]::IsNullOrWhiteSpace($AndroidSdkPath)) {
  if ($env:ANDROID_HOME) {
    $AndroidSdkPath = $env:ANDROID_HOME
  } elseif ($env:ANDROID_SDK_ROOT) {
    $AndroidSdkPath = $env:ANDROID_SDK_ROOT
  } else {
    $AndroidSdkPath = Join-Path $env:LOCALAPPDATA "Android\Sdk"
  }
}

if (-not (Test-Path $AndroidSdkPath)) {
  throw "Android SDK not found at '$AndroidSdkPath'. Install Android Studio + Android SDK, then rerun."
}

$env:ANDROID_HOME = $AndroidSdkPath
$env:ANDROID_SDK_ROOT = $AndroidSdkPath

if ($appUrlValue) {
  $env:CAP_APP_URL = $appUrlValue
  Write-Output "Using remote app URL: $appUrlValue"
} else {
  if (Test-Path Env:CAP_APP_URL) {
    Remove-Item Env:CAP_APP_URL
  }
  Write-Output "Using bundled local web assets for app shell."
}

$runtimeConfigPath = Join-Path $repoRootDir "public\runtime-config.js"
$escapedApiBase = $apiBaseValue.Replace('\', '\\').Replace('"', '\"')
$runtimeConfigContent = @(
  "// Generated by mobile/build-android.ps1",
  "window.__API_BASE__ = `"$escapedApiBase`";"
) -join "`r`n"
Set-Content -Path $runtimeConfigPath -Value $runtimeConfigContent -Encoding ASCII

if ($apiBaseValue) {
  Write-Output "Using API base: $apiBaseValue"
} else {
  Write-Output "No API base injected. App will ask for backend URL on first launch (native mode)."
}

$escapedSdkPath = $AndroidSdkPath.Replace("\", "\\").Replace(":", "\:")
$localProperties = "sdk.dir=$escapedSdkPath"
$localPropertiesPath = Join-Path $repoMobileDir "android\local.properties"
Set-Content -Path $localPropertiesPath -Value $localProperties -Encoding ASCII

Push-Location $repoMobileDir
try {
  npx cap sync android
  if ($LASTEXITCODE -ne 0) {
    throw "Capacitor sync failed."
  }

  Push-Location (Join-Path $repoMobileDir "android")
  try {
    .\gradlew.bat assembleDebug
    if ($LASTEXITCODE -ne 0) {
      throw "Gradle APK build failed."
    }
  } finally {
    Pop-Location
  }
} finally {
  Pop-Location
}

$apkPath = Join-Path $repoMobileDir "android\app\build\outputs\apk\debug\app-debug.apk"
if (-not (Test-Path $apkPath)) {
  throw "Build completed but APK not found at $apkPath"
}

$friendlyApkPath = Join-Path $repoMobileDir "CricZone-debug.apk"
Copy-Item -Path $apkPath -Destination $friendlyApkPath -Force

Write-Output ""
Write-Output "APK ready:"
Write-Output $friendlyApkPath
